# Generated by Django 5.1.3 on 2024-12-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='users/', verbose_name='аватар'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_a_medic',
            field=models.BooleanField(default=False, verbose_name='это медик'),
        ),
    ]
