# Generated by Django 5.1.3 on 2024-12-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_a_medic_user_is_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='профессия'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='users/', verbose_name='фото'
            ),
        ),
    ]
