# Generated by Django 5.1.3 on 2025-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_profession_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(default=1, max_length=30, verbose_name="телефон"),
            preserve_default=False,
        ),
    ]
