# Generated by Django 5.1.3 on 2025-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Эл.почта")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "db_table": "optics_contact",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Публиковать"),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "optics_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("quote", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Публиковать"),
                ),
            ],
            options={
                "verbose_name": "Цитата",
                "verbose_name_plural": "Цитаты",
                "db_table": "optics_quote",
            },
        ),
    ]
