# Generated by Django 5.1.3 on 2025-01-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contact",
            table=None,
        ),
        migrations.AlterModelTable(
            name="feedback",
            table=None,
        ),
        migrations.AlterModelTable(
            name="quote",
            table=None,
        ),
    ]
