# Generated by Django 5.1.3 on 2025-01-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0002_alter_contact_table_alter_feedback_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TunesDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=30, verbose_name="Ключ")),
                (
                    "value_int",
                    models.CharField(
                        blank=True, null=True, verbose_name="Целочисленное значение"
                    ),
                ),
                (
                    "value_char",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Строковое значение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тонкие настройки",
                "verbose_name_plural": "Тонкие настройки",
                "ordering": ["key"],
            },
        ),
    ]
