# Generated by Django 5.1.3 on 2025-01-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0003_tunesdict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tunesdict",
            name="key",
            field=models.CharField(max_length=30, unique=True, verbose_name="Ключ"),
        ),
    ]
