# Generated by Django 5.1.3 on 2025-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0004_alter_tunesdict_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunesdict",
            name="value_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Константа даты"
            ),
        ),
        migrations.AddField(
            model_name="tunesdict",
            name="value_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Константа времени"
            ),
        ),
    ]
