# Generated by Django 5.1.3 on 2025-01-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0005_tunesdict_value_date_tunesdict_value_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tunes/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Активно"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.TextField(blank=True, verbose_name="Цитата"),
        ),
    ]
