# Generated by Django 5.1.3 on 2025-01-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["service", "day", "time"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="comment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="day",
            field=models.DateField(verbose_name="День"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(verbose_name="Время"),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="День")),
                (
                    "begin_time",
                    models.TimeField(default="10:00", verbose_name="Начало приема"),
                ),
                (
                    "end_time",
                    models.TimeField(default="16:00", verbose_name="Конец приема"),
                ),
                (
                    "is_day_off",
                    models.BooleanField(default=False, verbose_name="Выходной"),
                ),
                (
                    "medic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Медик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписание",
                "ordering": ["medic", "day"],
            },
        ),
    ]
