# Generated by Django 5.1.3 on 2025-01-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0004_remove_schedule_is_day_off_schedule_is_working_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="SPH",
                    ),
                ),
                (
                    "cyl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="CYL",
                    ),
                ),
                (
                    "ax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="AX",
                    ),
                ),
                (
                    "pr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Pr",
                    ),
                ),
                (
                    "bas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="BAS",
                    ),
                ),
                (
                    "dp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="DP",
                    ),
                ),
                (
                    "add",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="ADD",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="schedule",
            name="is_working_day",
            field=models.BooleanField(default=True, verbose_name="Рабочий день"),
        ),
        migrations.CreateModel(
            name="ResultOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Рекомендации"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменен"),
                ),
                (
                    "od",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="od",
                        to="appointment.eye",
                        verbose_name="OD",
                    ),
                ),
                (
                    "os",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="os",
                        to="appointment.eye",
                        verbose_name="OD",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="appointment.appointment",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат услуги",
                "verbose_name_plural": "Результаты услуг",
                "ordering": ["-created_at"],
            },
        ),
    ]
