# Generated by Django 5.1.3 on 2025-01-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_remove_resultofservice_service_appointment_result"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eye",
            options={
                "verbose_name": "Результат измерений",
                "verbose_name_plural": "Результаты измерений",
            },
        ),
    ]
