# Generated by Django 5.1.3 on 2025-01-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0007_alter_eye_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultofservice",
            name="os",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="os",
                to="appointment.eye",
                verbose_name="OS",
            ),
        ),
    ]
