# Generated by Django 5.1.3 on 2024-12-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parameter',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Параметр'
            ),
        ),
    ]
