# Generated by Django 5.1.3 on 2024-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0006_category_active_on_main_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('quote', models.TextField(blank=True, verbose_name='Сообщение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публиковать')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
    ]
