# Generated by Django 5.1.3 on 2024-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0007_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
