# Generated by Django 5.1.3 on 2024-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0009_contact_service_image_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публиковать'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
    ]
