# Generated by Django 5.1.3 on 2024-12-18 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0010_service_is_published_alter_service_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='medic',
            field=models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
