# Generated by Django 5.1.3 on 2025-01-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("optics", "0014_delete_contact_delete_feedback_delete_quote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResultOfService",
        ),
    ]
